### ISSUE TITLE
Set a GenServer name in start_link

### ISSUE THREAD

**Issue by mattraykowski** [koudelka/slacker#3]
It would be helpful if the start_link defined by the macro included the name option:

`GenServer.start_link(__MODULE__, api_token, name: __MODULE__)`

The default `say` method is useful if you store the Slacker pid somewhere but I'd rather write "API" methods like this:

`
def say(channel, message) do
  GenServer.cast(__MODULE__, {:send_message, channel, message })
end
`

I am new to Elixir/OTP so I might be writing a bit of an anti-pattern and not know it.

**Comment by koudelka** [comment]
Hey @mattraykowski,

I've pushed version `0.0.2` to hex, allowing spawn options to be passed through to `start_link/3`.

You should be able to do `MySweetBot.start_link("your_api_key", name: MySweetBot)`.

I want to leave open the option to run the same bot on multiple Slack teams, so I don't want to automatically register the bot's module name. You'll still have to pass the registered name through to `say/3`.

If you know that you're only going to run one instance of that module, you could include a macro to implement your `say/2`:

```
defmacro say(channel, message) do
  quote do
    unquote(__MODULE__).say(unquote(__MODULE__), unquote(channel), unquote(message))
  end
end
```

You could similarly implement `start_link/1` to automatically name your bot `__MODULE__`.

Hope that helps!

**Comment by mattraykowski** [comment]
Thanks, this works even better!

**Comment by koudelka** [comment]
Just as a note, since you mentioned that you're new to Elixir, `Process.register/2` may help you in your journeys, too. :) 

http://elixir-lang.org/docs/stable/elixir/Process.html#register/2
